### PR TITLE
PICS refining.

### PR DESCRIPTION
**Pull request by JoelRedstone**

### CODE REVIEW

**Comment by JoelRedstone** [comment]
@grafnu PTAL

**Comment by grafnu** [comment]
Joel -- this is showing with conflicting files?

**Comment by JoelRedstone** [comment]
It seemed that you changed your code. 
Who responsibility is it to resolve the conflict? 
mine or yours?

**Comment by grafnu** [comment]
Maybe you need to rebase or merge the changes from the master branch?  If you look at your commit history, you haven't updated/merged since the Apr 1st commit. Generally speaking, it's the responsibility of the downstream branch to clean things up to fit in to the upstream branch.

```
$ git log -n 1 `git merge-base master redstone/master`
commit 6abd3cfcfe6cfb95f444638515a0b21f547a1202
Author: Trevor Pering <peringknife@google.com>
Date:   Mon Apr 1 11:19:33 2019 -0700

    Updating with more consistent output
$ git log -n 1 src/main/java/com/serotonin/bacnet4j/test/BacnetDriver.java
commit 8583c052e7765815b3716788a7c1bf7cd0565597
Author: Joel Ureellanah <45947249+JoelRedstone@users.noreply.github.com>
Date:   Sat Apr 6 01:10:45 2019 +0100

    Cleanup for DAQ tests

```

**Pull request closed without merging**
